version: 2.1
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-
      - run: sbt test:compile
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
      - run: sbt ";checkFix; checkFmt; test"
      - run: |
            mkdir target/reports
            cp core/target/test-reports/* rest-ui/target/test-reports/*  service-discovery/docker/target/test-reports/* service-discovery/docker/target/test-reports/* target/test-reports
      - store_test_results:
          path: target/test-reports
  release:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-
      - run: sbt compile
      - run: |
            cd rest-ui/
            npm install
      - save_cache:
          paths:
            - ~/.m2
            - ~/repo/rest-ui/rest-ui/node_modules
          key: v1-dependencies--{{ checksum "build.sbt" }}
      - run: echo $GITHUB_TOKEN | docker login docker.pkg.github.com -u MaethorNaur --password-stdin
      - run: sbt ";project rest-ui; release with-defaults"
workflows:
  version: 2
  test_on_branch:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
  release_on_master:
    jobs:
      - release:
          filters:
            branches:
              only:
                - master
            tags:
              ignore:
                - /v.+/
