name: Hugo
on:
  push:

    paths:
      - 'site/**'
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Deploy the site
        uses: MaethorNaur/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.79.1
          TARGET_REPO: UnisonUI/unisonui.github.io
          TARGET_BRANCH: master
          TOKEN: ${{ secrets.TOKEN }}
          CNAME: unisonui.tech
