name: Hugo
on:
  push:

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install tools
        run: npm install -g postcss postcss-cli esbuild
      - name: Install tools
        run: npm i
        working-directory: site
      - name: Deploy the site
        uses: MaethorNaur/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.79.1
          TARGET_REPO: UnisonUI/unisonui.github.io
          TARGET_BRANCH: master
          TOKEN: ${{ secrets.TOKEN }}
          CNAME: unisonui.tech
