name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Restore coursier cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/coursier/v1
        key: ${{ runner.os }}-coursier-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('project/Dependencies.scala') }}
        restore-keys: ${{ runner.os }}-coursier-
    - name: Restore m2 cache
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('project/Dependencies.scala') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Run tests
      run: sbt ";checkFix; checkFmt; coverage; test; coverageReport; coverageAggregate"
    - name: Copy test reports
      run: |
        mkdir target/test-reports
        cp core/target/test-reports/* target/test-reports || true
        cp rest-ui/target/test-reports/* target/test-reports || true
        cp service-discovery/docker/target/test-reports/* target/test-reports || true
        cp service-discovery/kubernetes/target/test-reports/* target/test-reports || true
    - name: Codecov
      uses: codecov/codecov-action@v1.0.13
    - name: action-slack
      uses: 8398a7/action-slack@v3.7.0
      with:
        status: ${{ job.status }}
        fields: message,commit,author
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
